spring:
  profiles:
    active: ${APP_PROFILE:test}
  jpa:
    open-in-view: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}

server:
  port: 8080

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:myclientid}
      client-secret: ${CLIENT_SECRET:myclientsecret}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}

aws:
  access_key_id: ${AWS-KEY:empty}
  secret_access_key: ${AWS-SECRET:empty}

s3:
  bucket: ${DSCATALOG_BUCKET_NAME:empty}
  region: ${DSCATALOG_BUCKET_REGION:sa-east-1}
