spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hibernate:
      ddl-auto: update
    
server:
  port: 8080
